$ANSIBLE_VAULT;1.1;AES256
38313038333832313632643136666336383436373363636464316132643530393433393931646662
6265333432663461663162633261383433316238616237310a303461306332313561356461633964
62396332653333316139663661613237373038636231663838333837313137666563373233343737
3336373435363565360a316135383866316531313531373566633939636236393630643235303539
38393635323231626666633830316535346365616531303233313337323165616566373938333464
39646432306365383262326634396161366564336538633262376430366237376638353532623132
30306135333666356437376165643962633131356435363937353464386438653539373133373838
65343763663731626666626162616536363637333434626462616236313737666134613037363961
34653065663665323164623130373835613262306334323063303239313763656661666338666361
65646263643337313132643830643936646535323033383564656638366631376565363564616231
66393533393139616261313266643563346266613631653464306538316465363131643165633832
36396665363239383663343862613034616533366339383836663834356632656336626666626166
32373839633561353232323333656130333738653639623234636165353861346330303461393438
32363865393866396332633664333633663661616535353139656262626263643732333730346138
31656261336563386164386366376239346233653963306631363633636239346536656664646232
30626233353735343461343935313262366132373365636662386234643339623138656662633331
32633263383563643235363465653766373665653361353937646436333639343862333436393463
37373261386164336136633865343137343765396332653364393032663139333338623937313532
64323031643764343962396233623636623630373761633135313037663431393335613035626666
38363361363264383831616136653963373666393137383439373537346166376531373563373461
36373436346662653963376563666365613737386162626632393233613638613336
